# XS-0130 Programación para Estadística II
## Solucionario para Práctica integrada — Estructuras de datos, funciones, NumPy y Pandas

**Universidad de Costa Rica — Escuela de Estadística**

### Caso de estudio: hábitos de estudio y rendimiento académico

Usted trabajará con un conjunto pequeño de registros académicos simulados. La meta es recorrer un flujo de análisis reproducible: organizar datos, definir funciones, trabajar con archivos, aplicar NumPy y finalmente analizar una tabla con Pandas.

> **Metodología:** ejecute las celdas en orden. En cada actividad escriba el código solicitado. No modifique la celda de datos base.

## 1. Preparación del entorno

In [1]:
import numpy as np
import pandas as pd
import json

print('NumPy:', np.__version__)
print('Pandas:', pd.__version__)

NumPy: 2.1.3
Pandas: 2.2.3

## 2. Datos base del caso

In [2]:
registros = [
    {"id": 1, "carrera": "Estadística", "modalidad": "Presencial", "horas_estudio": 8.5, "horas_sueno": 7.0, "asistencia": 95, "nota": 88},
    {"id": 2, "carrera": "Economía", "modalidad": "Híbrida", "horas_estudio": 5.0, "horas_sueno": 6.5, "asistencia": 82, "nota": 74},
    {"id": 3, "carrera": "Estadística", "modalidad": "Presencial", "horas_estudio": 10.0, "horas_sueno": 7.5, "asistencia": 98, "nota": 94},
    {"id": 4, "carrera": "Actuariales", "modalidad": "Presencial", "horas_estudio": 7.5, "horas_sueno": None, "asistencia": 90, "nota": 81},
    {"id": 5, "carrera": "Informática", "modalidad": "Híbrida", "horas_estudio": 4.0, "horas_sueno": 6.0, "asistencia": 75, "nota": 67},
    {"id": 6, "carrera": "Economía", "modalidad": "Presencial", "horas_estudio": None, "horas_sueno": 7.0, "asistencia": 88, "nota": 79},
    {"id": 7, "carrera": "Estadística", "modalidad": "Híbrida", "horas_estudio": 6.5, "horas_sueno": 6.5, "asistencia": 85, "nota": 83},
    {"id": 8, "carrera": "Actuariales", "modalidad": "Presencial", "horas_estudio": 9.0, "horas_sueno": 7.0, "asistencia": 92, "nota": 91},
    {"id": 9, "carrera": "Informática", "modalidad": "Presencial", "horas_estudio": 3.5, "horas_sueno": 5.5, "asistencia": 68, "nota": 58},
    {"id": 10, "carrera": "Economía", "modalidad": "Híbrida", "horas_estudio": 6.0, "horas_sueno": 6.0, "asistencia": 80, "nota": 72},
    {"id": 11, "carrera": "Estadística", "modalidad": "Presencial", "horas_estudio": 11.0, "horas_sueno": 8.0, "asistencia": 99, "nota": 97},
    {"id": 12, "carrera": "Actuariales", "modalidad": "Híbrida", "horas_estudio": 5.5, "horas_sueno": 6.5, "asistencia": 78, "nota": 76},
    {"id": 13, "carrera": "Informática", "modalidad": "Híbrida", "horas_estudio": None, "horas_sueno": 7.0, "asistencia": 84, "nota": 70},
    {"id": 14, "carrera": "Economía", "modalidad": "Presencial", "horas_estudio": 7.0, "horas_sueno": 7.5, "asistencia": 91, "nota": 85},
    {"id": 15, "carrera": "Estadística", "modalidad": "Híbrida", "horas_estudio": 4.5, "horas_sueno": 6.0, "asistencia": 73, "nota": 69},
    {"id": 16, "carrera": "Actuariales", "modalidad": "Presencial", "horas_estudio": 8.0, "horas_sueno": 7.0, "asistencia": 93, "nota": 89},
    {"id": 17, "carrera": "Informática", "modalidad": "Presencial", "horas_estudio": 6.0, "horas_sueno": None, "asistencia": 87, "nota": 78},
    {"id": 18, "carrera": "Economía", "modalidad": "Híbrida", "horas_estudio": 2.5, "horas_sueno": 5.5, "asistencia": 65, "nota": 61},
    {"id": 19, "carrera": "Estadística", "modalidad": "Presencial", "horas_estudio": 9.5, "horas_sueno": 7.0, "asistencia": 96, "nota": 92},
    {"id": 20, "carrera": "Actuariales", "modalidad": "Híbrida", "horas_estudio": 6.5, "horas_sueno": 6.5, "asistencia": 83, "nota": 80}
]

metadatos = {
    "institucion": "Universidad de Costa Rica",
    "curso": "XS-0130 Programación para Estadística II",
    "semestre": "II-2026",
    "corte_aprobacion": 70
}

print("Registros cargados:", len(registros))

Registros cargados: 20

---
# Parte I. Estructuras de datos, funciones y archivos

## Actividad 1. Reconocimiento de estructuras nativas

A partir de `registros` y `metadatos`:

1. Muestre el tipo de `registros`.
2. Muestre cuántos registros contiene.
3. Muestre el tipo del primer elemento de `registros`.
4. Muestre el primer registro completo.
5. Construya un **conjunto** llamado `carreras` con las carreras únicas.
6. Cree una **tupla** llamada `campos_clave` con: `("carrera", "nota", "asistencia")`.
7. Consulte en `metadatos` el valor asociado a `corte_aprobacion`.

In [3]:
print(type(registros))
print("Cantidad:", len(registros))
print(type(registros[0]))
print(registros[0])

carreras = set()
for registro in registros:
    carreras.add(registro["carrera"])

campos_clave = ("carrera", "nota", "asistencia")

print("Carreras únicas:", carreras)
print("Campos clave:", campos_clave)
print("Corte de aprobación:", metadatos["corte_aprobacion"])

<class 'list'>
Cantidad: 20
<class 'dict'>
{'id': 1, 'carrera': 'Estadística', 'modalidad': 'Presencial', 'horas_estudio': 8.5, 'horas_sueno': 7.0, 'asistencia': 95, 'nota': 88}
Carreras únicas: {'Estadística', 'Informática', 'Actuariales', 'Economía'}
Campos clave: ('carrera', 'nota', 'asistencia')
Corte de aprobación: 70

## Actividad 2. Funciones

Defina una función llamada `clasificar_nota(nota, corte=70)` que:

- reciba una nota;
- utilice `70` como corte predeterminado;
- retorne `"Aprobado"` si la nota es mayor o igual al corte;
- retorne `"Reprobado"` en caso contrario.

Luego:

1. Pruebe la función con `67`, `70` y `88`.
2. Recorra `registros` y construya una lista llamada `estados` con la clasificación de todas las notas.
3. Utilice `.count()` para indicar cuántos estudiantes aprobaron y cuántos reprobaron.

In [4]:
def clasificar_nota(nota, corte=70):
    if nota >= corte:
        return "Aprobado"
    return "Reprobado"

print(clasificar_nota(67))
print(clasificar_nota(70))
print(clasificar_nota(88))

estados = []
for registro in registros:
    estados.append(clasificar_nota(registro["nota"]))

print("Aprobados:", estados.count("Aprobado"))
print("Reprobados:", estados.count("Reprobado"))

Reprobado
Aprobado
Aprobado
Aprobados: 16
Reprobados: 4

## Actividad 3. Escritura y lectura de archivos

Realice dos tareas:

**A. Archivo de texto**
1. Cree `contexto_practica.txt`.
2. Escriba al menos tres líneas: curso, semestre y cantidad de registros.
3. Abra nuevamente el archivo en modo lectura y muestre su contenido.

**B. Archivo JSON**
1. Guarde `registros` en `registros_academicos.json` usando `json.dump()`.
2. Lea el JSON en una variable llamada `registros_json`.
3. Verifique que tenga la misma cantidad de elementos que `registros`.

In [5]:
with open("contexto_practica.txt", "w", encoding="utf-8") as f:
    f.write(f"Curso: {metadatos['curso']}\n")
    f.write(f"Semestre: {metadatos['semestre']}\n")
    f.write(f"Cantidad de registros: {len(registros)}\n")

with open("contexto_practica.txt", "r", encoding="utf-8") as f:
    contenido = f.read()

print(contenido)

with open("registros_academicos.json", "w", encoding="utf-8") as f:
    json.dump(registros, f, ensure_ascii=False, indent=4)

with open("registros_academicos.json", "r", encoding="utf-8") as f:
    registros_json = json.load(f)

print("Cantidad original:", len(registros))
print("Cantidad desde JSON:", len(registros_json))

Curso: XS-0130 Programación para Estadística II
Semestre: II-2026
Cantidad de registros: 20

Cantidad original: 20
Cantidad desde JSON: 20

---
# Parte II. NumPy

## Actividad 4. Creación, dimensiones e indexación

1. Construya un arreglo NumPy llamado `notas` con las notas contenidas en `registros`.
2. Muestre el arreglo y su tipo.
3. Consulte `shape`, `ndim` y `size`.
4. Muestre las primeras cuatro notas.
5. Muestre las últimas tres notas.

In [6]:
notas = np.array([registro["nota"] for registro in registros])

print(notas)
print(type(notas))
print("shape:", notas.shape)
print("ndim:", notas.ndim)
print("size:", notas.size)
print("Primeras cuatro:", notas[:4])
print("Últimas tres:", notas[-3:])

[88 74 94 81 67 79 83 91 58 72 97 76 70 85 69 89 78 61 92 80]
<class 'numpy.ndarray'>
shape: (20,)
ndim: 1
size: 20
Primeras cuatro: [88 74 94 81]
Últimas tres: [61 92 80]

## Actividad 5. Vectorización y máscaras booleanas

Trabaje **sin ciclos** sobre `notas`:

1. Cree `notas_ajustadas` sumando 3 puntos a todas las notas.
2. Cree `notas_proporcion` dividiendo las notas entre 100.
3. Cree una máscara para notas mayores o iguales a 70 y úsela para obtener `notas_aprobadas`.
4. Obtenga las notas menores a 70.
5. Obtenga las notas entre 70 y 85, inclusive.
6. Muestre cuántas notas aprobaron.

In [7]:
notas_ajustadas = notas + 3
notas_proporcion = notas / 100

mascara_aprobados = notas >= 70
notas_aprobadas = notas[mascara_aprobados]
notas_reprobadas = notas[notas < 70]
notas_70_85 = notas[(notas >= 70) & (notas <= 85)]

print("Ajustadas:", notas_ajustadas)
print("Proporción:", notas_proporcion)
print("Aprobadas:", notas_aprobadas)
print("Reprobadas:", notas_reprobadas)
print("Entre 70 y 85:", notas_70_85)
print("Cantidad aprobada:", len(notas_aprobadas))

Ajustadas: [ 91  77  97  84  70  82  86  94  61  75 100  79  73  88  72  92  81  64
  95  83]
Proporción: [0.88 0.74 0.94 0.81 0.67 0.79 0.83 0.91 0.58 0.72 0.97 0.76 0.7  0.85
 0.69 0.89 0.78 0.61 0.92 0.8 ]
Aprobadas: [88 74 94 81 79 83 91 72 97 76 70 85 89 78 92 80]
Reprobadas: [67 58 69 61]
Entre 70 y 85: [74 81 79 83 72 76 70 85 78 80]
Cantidad aprobada: 16

## Actividad 6. Estadística descriptiva con NumPy

Calcule para `notas`:

- media;
- mediana;
- desviación estándar;
- mínimo;
- máximo;
- rango (`máximo - mínimo`).

In [8]:
media_notas = np.mean(notas)
mediana_notas = np.median(notas)
desv_notas = np.std(notas)
min_notas = np.min(notas)
max_notas = np.max(notas)
rango_notas = max_notas - min_notas

print("Media:", media_notas)
print("Mediana:", mediana_notas)
print("Desviación estándar:", desv_notas)
print("Mínimo:", min_notas)
print("Máximo:", max_notas)
print("Rango:", rango_notas)

Media: 79.2
Mediana: 79.5
Desviación estándar: 10.661144403862092
Mínimo: 58
Máximo: 97
Rango: 39

## Actividad 7. Matrices y operaciones por eje

La siguiente matriz tendrá dos columnas: **asistencia** y **nota**.

1. Construya `matriz_indicadores`.
2. Muestre su `shape` y `ndim`.
3. Calcule el promedio de cada columna con `axis=0`.
4. Calcule el máximo de cada columna con `axis=0`.
5. Calcule el promedio por fila con `axis=1` y muestre únicamente los primeros cinco resultados.

> Interprete con cuidado: un promedio por fila mezcla dos indicadores con escalas similares, pero conceptualmente diferentes.

In [9]:
matriz_indicadores = np.array([
    [registro["asistencia"], registro["nota"]]
    for registro in registros
])

print("shape:", matriz_indicadores.shape)
print("ndim:", matriz_indicadores.ndim)
print("Promedio por columna:", np.mean(matriz_indicadores, axis=0))
print("Máximo por columna:", np.max(matriz_indicadores, axis=0))

promedio_fila = np.mean(matriz_indicadores, axis=1)
print("Primeros cinco promedios por fila:", promedio_fila[:5])

shape: (20, 2)
ndim: 2
Promedio por columna: [85.1 79.2]
Máximo por columna: [99 97]
Primeros cinco promedios por fila: [91.5 78.  96.  85.5 71. ]

---
# Parte III. Pandas

## Actividad 8. Creación y exploración inicial

1. Cree un DataFrame `df` a partir de `registros`.
2. Muestre las primeras cinco filas.
3. Consulte `shape`.
4. Utilice `info()`.
5. Utilice `describe()` para resumir las variables numéricas.

In [10]:
df = pd.DataFrame(registros)

display(df.head())
print("Dimensiones:", df.shape)

print("\nInformación:")
df.info()

print("\nResumen descriptivo:")
display(df.describe())

   id      carrera   modalidad  horas_estudio  horas_sueno  asistencia  nota
0   1  Estadística  Presencial            8.5          7.0          95    88
1   2     Economía     Híbrida            5.0          6.5          82    74
2   3  Estadística  Presencial           10.0          7.5          98    94
3   4  Actuariales  Presencial            7.5          NaN          90    81
4   5  Informática     Híbrida            4.0          6.0          75    67

Dimensiones: (20, 7)

Información:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             20 non-null     int64
 1   carrera        20 non-null     object
 2   modalidad      20 non-null     object
 3   horas_estudio  18 non-null     float64
 4   horas_sueno    18 non-null     float64
 5   asistencia     20 non-null     int64
 6   nota           20 non-null     int64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.2+ KB

Resumen descriptivo:

             id  horas_estudio  horas_sueno  asistencia       nota
count  20.00000      18.000000    18.000000   20.000000  20.000000
mean   10.50000       6.694444     6.666667   85.100000  79.200000
std     5.91608       2.346079     0.685994    9.716508  10.938103
min     1.00000       2.500000     5.500000   65.000000  58.000000
25%     5.75000       5.125000     6.125000   79.500000  71.500000
50%    10.50000       6.500000     6.750000   86.000000  79.500000
75%    15.25000       8.375000     7.000000   92.250000  88.250000
max    20.00000      11.000000     8.000000   99.000000  97.000000

## Actividad 9. Selección con columnas, `loc` e `iloc`

Obtenga:

1. Solo la columna `nota`.
2. Las columnas `carrera`, `modalidad` y `nota`.
3. Con `loc`, las filas con etiquetas de 0 a 4 y las columnas `carrera` y `nota`.
4. Con `iloc`, las primeras tres filas y las columnas correspondientes a `id`, `asistencia` y `nota`.
5. Con `iloc`, la última fila completa.

In [11]:
display(df["nota"])
display(df[["carrera", "modalidad", "nota"]])

display(df.loc[0:4, ["carrera", "nota"]])
display(df.iloc[0:3, [0, 5, 6]])
display(df.iloc[-1, :])

0     88
1     74
2     94
3     81
4     67
5     79
6     83
7     91
8     58
9     72
10    97
11    76
12    70
13    85
14    69
15    89
16    78
17    61
18    92
19    80
Name: nota, dtype: int64

        carrera   modalidad  nota
0   Estadística  Presencial    88
1      Economía     Híbrida    74
2   Estadística  Presencial    94
3   Actuariales  Presencial    81
4   Informática     Híbrida    67
5      Economía  Presencial    79
6   Estadística     Híbrida    83
7   Actuariales  Presencial    91
8   Informática  Presencial    58
9      Economía     Híbrida    72
10  Estadística  Presencial    97
11  Actuariales     Híbrida    76
12  Informática     Híbrida    70
13     Economía  Presencial    85
14  Estadística     Híbrida    69
15  Actuariales  Presencial    89
16  Informática  Presencial    78
17     Economía     Híbrida    61
18  Estadística  Presencial    92
19  Actuariales     Híbrida    80

       carrera  nota
0  Estadística    88
1     Economía    74
2  Estadística    94
3  Actuariales    81
4  Informática    67

   id  asistencia  nota
0   1          95    88
1   2          82    74
2   3          98    94

id                        20
carrera          Actuariales
modalidad            Híbrida
horas_estudio            6.5
horas_sueno              6.5
asistencia                83
nota                      80
Name: 19, dtype: object

## Actividad 10. Valores faltantes

1. Identifique cuántos valores faltantes existen por columna.
2. Cree `df_limpio` como una copia de `df`.
3. Reemplace los faltantes de `horas_estudio` con la **mediana** de esa columna.
4. Reemplace los faltantes de `horas_sueno` con la **media** de esa columna.
5. Compruebe que esas dos columnas ya no tengan valores faltantes.

In [12]:
print("Faltantes por columna:")
print(df.isna().sum())

df_limpio = df.copy()

df_limpio["horas_estudio"] = df_limpio["horas_estudio"].fillna(
    df_limpio["horas_estudio"].median()
)

df_limpio["horas_sueno"] = df_limpio["horas_sueno"].fillna(
    df_limpio["horas_sueno"].mean()
)

print("\nFaltantes después de limpiar:")
print(df_limpio[["horas_estudio", "horas_sueno"]].isna().sum())

Faltantes por columna:
id               0
carrera          0
modalidad        0
horas_estudio    2
horas_sueno      2
asistencia       0
nota             0
dtype: int64

Faltantes después de limpiar:
horas_estudio    0
horas_sueno      0
dtype: int64

## Actividad 11. Filtros con condiciones

Sobre `df_limpio`, obtenga:

1. Estudiantes con nota mayor o igual a 85.
2. Estudiantes de **Estadística** con asistencia mayor o igual a 90.
3. Estudiantes en modalidad **Híbrida** con nota entre 70 y 85, inclusive.
4. Estudiantes de **Economía o Actuariales** con nota mayor o igual a 80.

Recuerde utilizar paréntesis cuando combine condiciones.

In [13]:
filtro_1 = df_limpio[df_limpio["nota"] >= 85]

filtro_2 = df_limpio[
    (df_limpio["carrera"] == "Estadística") &
    (df_limpio["asistencia"] >= 90)
]

filtro_3 = df_limpio[
    (df_limpio["modalidad"] == "Híbrida") &
    (df_limpio["nota"] >= 70) &
    (df_limpio["nota"] <= 85)
]

filtro_4 = df_limpio[
    ((df_limpio["carrera"] == "Economía") |
     (df_limpio["carrera"] == "Actuariales")) &
    (df_limpio["nota"] >= 80)
]

display(filtro_1)
display(filtro_2)
display(filtro_3)
display(filtro_4)

    id      carrera   modalidad  horas_estudio  horas_sueno  asistencia  nota
0    1  Estadística  Presencial            8.5          7.0          95    88
2    3  Estadística  Presencial           10.0          7.5          98    94
7    8  Actuariales  Presencial            9.0          7.0          92    91
10  11  Estadística  Presencial           11.0          8.0          99    97
13  14     Economía  Presencial            7.0          7.5          91    85
15  16  Actuariales  Presencial            8.0          7.0          93    89
18  19  Estadística  Presencial            9.5          7.0          96    92

    id      carrera   modalidad  horas_estudio  horas_sueno  asistencia  nota
0    1  Estadística  Presencial            8.5          7.0          95    88
2    3  Estadística  Presencial           10.0          7.5          98    94
10  11  Estadística  Presencial           11.0          8.0          99    97
18  19  Estadística  Presencial            9.5          7.0          96    92

    id      carrera modalidad  horas_estudio  horas_sueno  asistencia  nota
1    2     Economía   Híbrida            5.0          6.5          82    74
6    7  Estadística   Híbrida            6.5          6.5          85    83
9   10     Economía   Híbrida            6.0          6.0          80    72
11  12  Actuariales   Híbrida            5.5          6.5          78    76
12  13  Informática   Híbrida            6.5          7.0          84    70
19  20  Actuariales   Híbrida            6.5          6.5          83    80

    id      carrera   modalidad  horas_estudio  horas_sueno  asistencia  nota
3    4  Actuariales  Presencial            7.5     6.666667          90    81
7    8  Actuariales  Presencial            9.0     7.000000          92    91
13  14     Economía  Presencial            7.0     7.500000          91    85
15  16  Actuariales  Presencial            8.0     7.000000          93    89
19  20  Actuariales     Híbrida            6.5     6.500000          83    80

## Actividad 12. Crear y transformar variables

Agregue a `df_limpio`:

1. `nota_ajustada`: nota original + 3.
2. `estado`: `"Aprobado"` si `nota >= 70`; de lo contrario `"Reprobado"`, usando `np.where()`.
3. `estudio_alto`: `"Sí"` si `horas_estudio >= 7`; de lo contrario `"No"`, usando `np.where()`.
4. Convierta `nota` a tipo `float`.
5. Muestre las primeras cinco filas con las nuevas variables.

In [14]:
df_limpio["nota_ajustada"] = df_limpio["nota"] + 3

df_limpio["estado"] = np.where(
    df_limpio["nota"] >= 70,
    "Aprobado",
    "Reprobado"
)

df_limpio["estudio_alto"] = np.where(
    df_limpio["horas_estudio"] >= 7,
    "Sí",
    "No"
)

df_limpio["nota"] = df_limpio["nota"].astype(float)

display(df_limpio.head())

,id,carrera,modalidad,horas_estudio,horas_sueno,asistencia,nota,nota_ajustada,estado,estudio_alto
0,1,Estadística,Presencial,8.5,7.000000,95,88.0,91,Aprobado,Sí
1,2,Economía,Híbrida,5.0,6.500000,82,74.0,77,Aprobado,No
2,3,Estadística,Presencial,10.0,7.500000,98,94.0,97,Aprobado,Sí
3,4,Actuariales,Presencial,7.5,6.666667,90,81.0,84,Aprobado,Sí
4,5,Informática,Híbrida,4.0,6.000000,75,67.0,70,Reprobado,No

## Actividad 13. Ordenamiento

1. Cree `ranking` ordenando de mayor a menor por `nota`.
2. Reinicie el índice de `ranking`.
3. Muestre los cinco primeros registros con `id`, `carrera` y `nota`.
4. Cree otra tabla ordenada primero por `carrera` de A a Z y, dentro de cada carrera, por `nota` de mayor a menor.

In [15]:
ranking = df_limpio.sort_values("nota", ascending=False)
ranking = ranking.reset_index(drop=True)

display(ranking[["id", "carrera", "nota"]].head())

orden_carrera = df_limpio.sort_values(
    ["carrera", "nota"],
    ascending=[True, False]
)

display(orden_carrera[["id", "carrera", "nota"]])

   id      carrera  nota
0  11  Estadística  97.0
1   3  Estadística  94.0
2  19  Estadística  92.0
3   8  Actuariales  91.0
4  16  Actuariales  89.0

    id      carrera  nota
7    8  Actuariales  91.0
15  16  Actuariales  89.0
3    4  Actuariales  81.0
19  20  Actuariales  80.0
11  12  Actuariales  76.0
13  14     Economía  85.0
5    6     Economía  79.0
1    2     Economía  74.0
9   10     Economía  72.0
17  18     Economía  61.0
10  11  Estadística  97.0
2    3  Estadística  94.0
18  19  Estadística  92.0
0    1  Estadística  88.0
6    7  Estadística  83.0
14  15  Estadística  69.0
16  17  Informática  78.0
12  13  Informática  70.0
4    5  Informática  67.0
8    9  Informática  58.0

## Actividad 14. Agrupaciones

Construya `resumen_carrera` agrupando por `carrera` e incluyendo:

- promedio de `nota`;
- mediana de `nota`;
- nota máxima;
- promedio de `horas_estudio`;
- cantidad de estudiantes.

Luego construya un segundo resumen por `modalidad` con:

- promedio de `nota`;
- promedio de `asistencia`;
- cantidad de estudiantes.

In [16]:
resumen_carrera = df_limpio.groupby("carrera").agg(
    promedio_nota=("nota", "mean"),
    mediana_nota=("nota", "median"),
    nota_maxima=("nota", "max"),
    promedio_horas_estudio=("horas_estudio", "mean"),
    cantidad=("id", "count")
)

resumen_modalidad = df_limpio.groupby("modalidad").agg(
    promedio_nota=("nota", "mean"),
    promedio_asistencia=("asistencia", "mean"),
    cantidad=("id", "count")
)

display(resumen_carrera)
display(resumen_modalidad)

,promedio_nota,mediana_nota,nota_maxima,promedio_horas_estudio,cantidad
carrera,,,,,
Actuariales,83.400000,81.0,91.0,7.300000,5
Economía,74.200000,74.0,85.0,5.400000,5
Estadística,87.166667,90.0,97.0,8.333333,6
Informática,68.250000,68.5,78.0,5.000000,4

            promedio_nota  promedio_asistencia  cantidad
modalidad
Híbrida         72.444444            78.333333         9
Presencial      84.727273            90.636364        11

## Actividad 15. Combinar tablas con `merge()`

Ejecute la tabla auxiliar:

```python
info_carreras = pd.DataFrame({
    "carrera": ["Estadística", "Economía", "Actuariales"],
    "area": ["Ciencias", "Ciencias Sociales", "Ciencias"],
    "codigo": ["EST", "ECO", "ACT"]
})
```

Observe que **Informática no aparece** en la tabla auxiliar.

Luego:

1. Haga un `merge()` con `how="inner"`.
2. Haga otro con `how="left"`.
3. Compare la cantidad de filas de ambos resultados.
4. Explique qué ocurrió con los registros de Informática.

In [17]:
info_carreras = pd.DataFrame({
    "carrera": ["Estadística", "Economía", "Actuariales"],
    "area": ["Ciencias", "Ciencias Sociales", "Ciencias"],
    "codigo": ["EST", "ECO", "ACT"]
})

merge_inner = df_limpio.merge(
    info_carreras,
    on="carrera",
    how="inner"
)

merge_left = df_limpio.merge(
    info_carreras,
    on="carrera",
    how="left"
)

print("Filas inner:", merge_inner.shape[0])
print("Filas left:", merge_left.shape[0])

display(merge_inner.head())
display(merge_left[merge_left["carrera"] == "Informática"])

Filas inner: 16
Filas left: 20

,id,carrera,modalidad,horas_estudio,horas_sueno,asistencia,nota,nota_ajustada,estado,estudio_alto,area,codigo
0,1,Estadística,Presencial,8.5,7.000000,95,88.0,91,Aprobado,Sí,Ciencias,EST
1,2,Economía,Híbrida,5.0,6.500000,82,74.0,77,Aprobado,No,Ciencias Sociales,ECO
2,3,Estadística,Presencial,10.0,7.500000,98,94.0,97,Aprobado,Sí,Ciencias,EST
3,4,Actuariales,Presencial,7.5,6.666667,90,81.0,84,Aprobado,Sí,Ciencias,ACT
4,6,Economía,Presencial,6.5,7.000000,88,79.0,82,Aprobado,No,Ciencias Sociales,ECO

,id,carrera,modalidad,horas_estudio,horas_sueno,asistencia,nota,nota_ajustada,estado,estudio_alto,area,codigo
4,5,Informática,Híbrida,4.0,6.000000,75,67.0,70,Reprobado,No,NaN,NaN
8,9,Informática,Presencial,3.5,5.500000,68,58.0,61,Reprobado,No,NaN,NaN
12,13,Informática,Híbrida,6.5,7.000000,84,70.0,73,Aprobado,No,NaN,NaN
16,17,Informática,Presencial,6.0,6.666667,87,78.0,81,Aprobado,No,NaN,NaN

**Explicación:** el `inner` conserva únicamente las filas cuya carrera tiene coincidencia en ambas tablas, por lo que elimina los registros de Informática. El `left` conserva todas las filas de `df_limpio`; para Informática, las columnas `area` y `codigo` quedan con valores faltantes (`NaN`).

## Actividad 16. Lectura y escritura con Pandas

1. Exporte `df_limpio` a `estudiantes_limpios.csv` sin índice.
2. Exporte `df_limpio` a `estudiantes_limpios.xlsx` sin índice.
3. Exporte `resumen_carrera` a `resumen_por_carrera.csv`.
4. Lea nuevamente `estudiantes_limpios.csv` en `df_releido`.
5. Muestre las primeras filas y compruebe que sus dimensiones coinciden con las de `df_limpio`.

In [18]:
df_limpio.to_csv("estudiantes_limpios.csv", index=False)
df_limpio.to_excel("estudiantes_limpios.xlsx", index=False)
resumen_carrera.to_csv("resumen_por_carrera.csv")

df_releido = pd.read_csv("estudiantes_limpios.csv")

display(df_releido.head())
print("Dimensiones originales:", df_limpio.shape)
print("Dimensiones releídas:", df_releido.shape)

,id,carrera,modalidad,horas_estudio,horas_sueno,asistencia,nota,nota_ajustada,estado,estudio_alto
0,1,Estadística,Presencial,8.5,7.000000,95,88.0,91,Aprobado,Sí
1,2,Economía,Híbrida,5.0,6.500000,82,74.0,77,Aprobado,No
2,3,Estadística,Presencial,10.0,7.500000,98,94.0,97,Aprobado,Sí
3,4,Actuariales,Presencial,7.5,6.666667,90,81.0,84,Aprobado,Sí
4,5,Informática,Híbrida,4.0,6.000000,75,67.0,70,Reprobado,No

Dimensiones originales: (20, 10)
Dimensiones releídas: (20, 10)

---
# Parte IV. Reto integrador

## Actividad 17. Identificación de estudiantes en riesgo

Construya una tabla llamada `riesgo` con estudiantes que cumplan **al menos una** de estas condiciones:

- `nota < 70`, o
- `asistencia < 75`.

Luego:

1. Conserve únicamente `id`, `carrera`, `modalidad`, `asistencia`, `nota` y `estado`.
2. Ordene de menor a mayor por `nota`.
3. Reinicie el índice.
4. Exporte la tabla como `estudiantes_en_riesgo.csv`.
5. Indique cuántos estudiantes aparecen en la tabla.

In [19]:
riesgo = df_limpio[
    (df_limpio["nota"] < 70) |
    (df_limpio["asistencia"] < 75)
][["id", "carrera", "modalidad", "asistencia", "nota", "estado"]]

riesgo = riesgo.sort_values("nota", ascending=True).reset_index(drop=True)
riesgo.to_csv("estudiantes_en_riesgo.csv", index=False)

display(riesgo)
print("Cantidad de estudiantes en riesgo:", riesgo.shape[0])

   id      carrera   modalidad  asistencia  nota     estado
0   9  Informática  Presencial          68  58.0  Reprobado
1  18     Economía     Híbrida          65  61.0  Reprobado
2   5  Informática     Híbrida          75  67.0  Reprobado
3  15  Estadística     Híbrida          73  69.0  Reprobado

Cantidad de estudiantes en riesgo: 4